const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT-USER',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    CHECL_USER_SESSION: 'CHECL_USER_SESSION' 
};

export default UserActionTypes;